services:
  db:
    image: postgres:15
    container_name: db
    command: -c listen_addresses='*'
    env_file:
      - .env
    ports:
      - "5431:5432"

  app:
    image: app
    container_name: app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - /var/log/myapp/:/app/logs
      - ./:/app
    ports:
      - "8000"
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis
    command: sh -c "touch /var/log/redis.log && redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - /var/log/myapp/:/var/log/myapp/redis_logs.log